import { log } from "node:console";
import path from "node:path";
const __dirname = import.meta.dirname;
const __filename = import.meta.filename;
log(path.sep);
log(path.resolve(__dirname, "files", "data.txt"));
log(path.join("big", "data", "db.json"));
log(path.resolve("big", ".///data", "db.json"));
log(path.parse(__filename));
log(path.extname(path.join(__dirname, "db.json")));
log(path.isAbsolute(__filename));
